<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \BlueFinch\Checkout\ViewModel\Assets $assetViewModel
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$assetViewModel = $block->getAssetViewModel();

$payByBank = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutRvvup::js/checkout/dist/components/PayByBank/PayByBank.min.js');
$styles = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutRvvup::js/checkout/dist/styles.css');

?>

<?php $scriptString = <<<script
    window.bluefinchCheckout = window.bluefinchCheckout || {};
    window.bluefinchCheckout.paymentMethods = window.bluefinchCheckout.paymentMethods || {};

    window.bluefinchCheckout.paymentMethods.Rvvup = "{$escaper->escapeJs($payByBank)}";
script; ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<link rel="stylesheet" href="<?= $escaper->escapeHtmlAttr($styles) ?>" />
